/* eslint-disable */
// AUTO-GENERATED by scripts/generate-preflop-matrix.mjs — do not edit by hand.
// 口径：6 人、其余 5 随机手、翻前 all-in 到河、chop、无 rake。trials=12000

export type PreflopKind = 'pair' | 'suited' | 'offsuit'
export type PreflopTier = 'S' | 'A' | 'B' | 'C' | 'D'

export interface PreflopCell {
  code: string
  kind: PreflopKind
  equity: number
  tier: PreflopTier
}

export interface PreflopMatrix {
  ranks: string[]
  meta: {
    players: number
    opponents: number
    model: string
    equityDefinition: string
    source: string
    version: string
    trials: number
    seed: string
    tierBreaks: Record<string, string>
    disclaimer: string
  }
  cells: PreflopCell[][]
}

export const PREFLOP_RANKS = ["A","K","Q","J","T","9","8","7","6","5","4","3","2"] as const

export const PREFLOP_MATRIX: PreflopMatrix = {
  "ranks": [
    "A",
    "K",
    "Q",
    "J",
    "T",
    "9",
    "8",
    "7",
    "6",
    "5",
    "4",
    "3",
    "2"
  ],
  "meta": {
    "players": 6,
    "opponents": 5,
    "model": "random_uniform_hole_cards",
    "equityDefinition": "preflop_allin_to_river_chop_no_rake",
    "source": "scripts/generate-preflop-matrix.mjs",
    "version": "1",
    "trials": 12000,
    "seed": "0x74657861",
    "tierBreaks": {
      "method": "percentile_desc",
      "S": "top ~5% (n=8)",
      "A": "next ~10% (n=17)",
      "B": "next ~20% (n=34)",
      "C": "next ~30% (n=51)",
      "D": "remainder"
    },
    "disclaimer": "近似参考，非实时胜率"
  },
  "cells": [
    [
      {
        "code": "AA",
        "kind": "pair",
        "equity": 0.4913,
        "tier": "S"
      },
      {
        "code": "AKs",
        "kind": "suited",
        "equity": 0.3077,
        "tier": "S"
      },
      {
        "code": "AQs",
        "kind": "suited",
        "equity": 0.2909,
        "tier": "S"
      },
      {
        "code": "AJs",
        "kind": "suited",
        "equity": 0.2832,
        "tier": "S"
      },
      {
        "code": "ATs",
        "kind": "suited",
        "equity": 0.2739,
        "tier": "A"
      },
      {
        "code": "A9s",
        "kind": "suited",
        "equity": 0.2441,
        "tier": "A"
      },
      {
        "code": "A8s",
        "kind": "suited",
        "equity": 0.2308,
        "tier": "A"
      },
      {
        "code": "A7s",
        "kind": "suited",
        "equity": 0.226,
        "tier": "B"
      },
      {
        "code": "A6s",
        "kind": "suited",
        "equity": 0.2131,
        "tier": "B"
      },
      {
        "code": "A5s",
        "kind": "suited",
        "equity": 0.2172,
        "tier": "B"
      },
      {
        "code": "A4s",
        "kind": "suited",
        "equity": 0.2145,
        "tier": "B"
      },
      {
        "code": "A3s",
        "kind": "suited",
        "equity": 0.2134,
        "tier": "B"
      },
      {
        "code": "A2s",
        "kind": "suited",
        "equity": 0.2035,
        "tier": "B"
      }
    ],
    [
      {
        "code": "AKo",
        "kind": "offsuit",
        "equity": 0.283,
        "tier": "A"
      },
      {
        "code": "KK",
        "kind": "pair",
        "equity": 0.4315,
        "tier": "S"
      },
      {
        "code": "KQs",
        "kind": "suited",
        "equity": 0.2756,
        "tier": "A"
      },
      {
        "code": "KJs",
        "kind": "suited",
        "equity": 0.2732,
        "tier": "A"
      },
      {
        "code": "KTs",
        "kind": "suited",
        "equity": 0.2558,
        "tier": "A"
      },
      {
        "code": "K9s",
        "kind": "suited",
        "equity": 0.2295,
        "tier": "B"
      },
      {
        "code": "K8s",
        "kind": "suited",
        "equity": 0.213,
        "tier": "B"
      },
      {
        "code": "K7s",
        "kind": "suited",
        "equity": 0.2038,
        "tier": "B"
      },
      {
        "code": "K6s",
        "kind": "suited",
        "equity": 0.2007,
        "tier": "B"
      },
      {
        "code": "K5s",
        "kind": "suited",
        "equity": 0.192,
        "tier": "B"
      },
      {
        "code": "K4s",
        "kind": "suited",
        "equity": 0.1924,
        "tier": "B"
      },
      {
        "code": "K3s",
        "kind": "suited",
        "equity": 0.1847,
        "tier": "C"
      },
      {
        "code": "K2s",
        "kind": "suited",
        "equity": 0.1835,
        "tier": "C"
      }
    ],
    [
      {
        "code": "AQo",
        "kind": "offsuit",
        "equity": 0.2671,
        "tier": "A"
      },
      {
        "code": "KQo",
        "kind": "offsuit",
        "equity": 0.251,
        "tier": "A"
      },
      {
        "code": "QQ",
        "kind": "pair",
        "equity": 0.3778,
        "tier": "S"
      },
      {
        "code": "QJs",
        "kind": "suited",
        "equity": 0.2669,
        "tier": "A"
      },
      {
        "code": "QTs",
        "kind": "suited",
        "equity": 0.2513,
        "tier": "A"
      },
      {
        "code": "Q9s",
        "kind": "suited",
        "equity": 0.2283,
        "tier": "B"
      },
      {
        "code": "Q8s",
        "kind": "suited",
        "equity": 0.2062,
        "tier": "B"
      },
      {
        "code": "Q7s",
        "kind": "suited",
        "equity": 0.1936,
        "tier": "B"
      },
      {
        "code": "Q6s",
        "kind": "suited",
        "equity": 0.1884,
        "tier": "B"
      },
      {
        "code": "Q5s",
        "kind": "suited",
        "equity": 0.1825,
        "tier": "C"
      },
      {
        "code": "Q4s",
        "kind": "suited",
        "equity": 0.1733,
        "tier": "C"
      },
      {
        "code": "Q3s",
        "kind": "suited",
        "equity": 0.1751,
        "tier": "C"
      },
      {
        "code": "Q2s",
        "kind": "suited",
        "equity": 0.1688,
        "tier": "C"
      }
    ],
    [
      {
        "code": "AJo",
        "kind": "offsuit",
        "equity": 0.2423,
        "tier": "A"
      },
      {
        "code": "KJo",
        "kind": "offsuit",
        "equity": 0.2382,
        "tier": "A"
      },
      {
        "code": "QJo",
        "kind": "offsuit",
        "equity": 0.2268,
        "tier": "B"
      },
      {
        "code": "JJ",
        "kind": "pair",
        "equity": 0.3304,
        "tier": "S"
      },
      {
        "code": "JTs",
        "kind": "suited",
        "equity": 0.2471,
        "tier": "A"
      },
      {
        "code": "J9s",
        "kind": "suited",
        "equity": 0.2278,
        "tier": "B"
      },
      {
        "code": "J8s",
        "kind": "suited",
        "equity": 0.2025,
        "tier": "B"
      },
      {
        "code": "J7s",
        "kind": "suited",
        "equity": 0.1917,
        "tier": "B"
      },
      {
        "code": "J6s",
        "kind": "suited",
        "equity": 0.178,
        "tier": "C"
      },
      {
        "code": "J5s",
        "kind": "suited",
        "equity": 0.1689,
        "tier": "C"
      },
      {
        "code": "J4s",
        "kind": "suited",
        "equity": 0.1611,
        "tier": "C"
      },
      {
        "code": "J3s",
        "kind": "suited",
        "equity": 0.1632,
        "tier": "C"
      },
      {
        "code": "J2s",
        "kind": "suited",
        "equity": 0.1626,
        "tier": "C"
      }
    ],
    [
      {
        "code": "ATo",
        "kind": "offsuit",
        "equity": 0.2361,
        "tier": "A"
      },
      {
        "code": "KTo",
        "kind": "offsuit",
        "equity": 0.2229,
        "tier": "B"
      },
      {
        "code": "QTo",
        "kind": "offsuit",
        "equity": 0.2167,
        "tier": "B"
      },
      {
        "code": "JTo",
        "kind": "offsuit",
        "equity": 0.2103,
        "tier": "B"
      },
      {
        "code": "TT",
        "kind": "pair",
        "equity": 0.2995,
        "tier": "S"
      },
      {
        "code": "T9s",
        "kind": "suited",
        "equity": 0.2251,
        "tier": "B"
      },
      {
        "code": "T8s",
        "kind": "suited",
        "equity": 0.2007,
        "tier": "B"
      },
      {
        "code": "T7s",
        "kind": "suited",
        "equity": 0.1859,
        "tier": "C"
      },
      {
        "code": "T6s",
        "kind": "suited",
        "equity": 0.1768,
        "tier": "C"
      },
      {
        "code": "T5s",
        "kind": "suited",
        "equity": 0.1557,
        "tier": "C"
      },
      {
        "code": "T4s",
        "kind": "suited",
        "equity": 0.1583,
        "tier": "C"
      },
      {
        "code": "T3s",
        "kind": "suited",
        "equity": 0.1537,
        "tier": "C"
      },
      {
        "code": "T2s",
        "kind": "suited",
        "equity": 0.1429,
        "tier": "D"
      }
    ],
    [
      {
        "code": "A9o",
        "kind": "offsuit",
        "equity": 0.196,
        "tier": "B"
      },
      {
        "code": "K9o",
        "kind": "offsuit",
        "equity": 0.1918,
        "tier": "B"
      },
      {
        "code": "Q9o",
        "kind": "offsuit",
        "equity": 0.1883,
        "tier": "B"
      },
      {
        "code": "J9o",
        "kind": "offsuit",
        "equity": 0.1848,
        "tier": "C"
      },
      {
        "code": "T9o",
        "kind": "offsuit",
        "equity": 0.1934,
        "tier": "B"
      },
      {
        "code": "99",
        "kind": "pair",
        "equity": 0.2641,
        "tier": "A"
      },
      {
        "code": "98s",
        "kind": "suited",
        "equity": 0.2069,
        "tier": "B"
      },
      {
        "code": "97s",
        "kind": "suited",
        "equity": 0.187,
        "tier": "C"
      },
      {
        "code": "96s",
        "kind": "suited",
        "equity": 0.1756,
        "tier": "C"
      },
      {
        "code": "95s",
        "kind": "suited",
        "equity": 0.1601,
        "tier": "C"
      },
      {
        "code": "94s",
        "kind": "suited",
        "equity": 0.14,
        "tier": "D"
      },
      {
        "code": "93s",
        "kind": "suited",
        "equity": 0.1458,
        "tier": "D"
      },
      {
        "code": "92s",
        "kind": "suited",
        "equity": 0.1415,
        "tier": "D"
      }
    ],
    [
      {
        "code": "A8o",
        "kind": "offsuit",
        "equity": 0.1928,
        "tier": "B"
      },
      {
        "code": "K8o",
        "kind": "offsuit",
        "equity": 0.1697,
        "tier": "C"
      },
      {
        "code": "Q8o",
        "kind": "offsuit",
        "equity": 0.1655,
        "tier": "C"
      },
      {
        "code": "J8o",
        "kind": "offsuit",
        "equity": 0.1671,
        "tier": "C"
      },
      {
        "code": "T8o",
        "kind": "offsuit",
        "equity": 0.1718,
        "tier": "C"
      },
      {
        "code": "98o",
        "kind": "offsuit",
        "equity": 0.165,
        "tier": "C"
      },
      {
        "code": "88",
        "kind": "pair",
        "equity": 0.2312,
        "tier": "A"
      },
      {
        "code": "87s",
        "kind": "suited",
        "equity": 0.1879,
        "tier": "B"
      },
      {
        "code": "86s",
        "kind": "suited",
        "equity": 0.1782,
        "tier": "C"
      },
      {
        "code": "85s",
        "kind": "suited",
        "equity": 0.1595,
        "tier": "C"
      },
      {
        "code": "84s",
        "kind": "suited",
        "equity": 0.1495,
        "tier": "C"
      },
      {
        "code": "83s",
        "kind": "suited",
        "equity": 0.1346,
        "tier": "D"
      },
      {
        "code": "82s",
        "kind": "suited",
        "equity": 0.1305,
        "tier": "D"
      }
    ],
    [
      {
        "code": "A7o",
        "kind": "offsuit",
        "equity": 0.1861,
        "tier": "C"
      },
      {
        "code": "K7o",
        "kind": "offsuit",
        "equity": 0.1591,
        "tier": "C"
      },
      {
        "code": "Q7o",
        "kind": "offsuit",
        "equity": 0.1463,
        "tier": "D"
      },
      {
        "code": "J7o",
        "kind": "offsuit",
        "equity": 0.1526,
        "tier": "C"
      },
      {
        "code": "T7o",
        "kind": "offsuit",
        "equity": 0.1469,
        "tier": "D"
      },
      {
        "code": "97o",
        "kind": "offsuit",
        "equity": 0.1478,
        "tier": "D"
      },
      {
        "code": "87o",
        "kind": "offsuit",
        "equity": 0.1575,
        "tier": "C"
      },
      {
        "code": "77",
        "kind": "pair",
        "equity": 0.2155,
        "tier": "B"
      },
      {
        "code": "76s",
        "kind": "suited",
        "equity": 0.1794,
        "tier": "C"
      },
      {
        "code": "75s",
        "kind": "suited",
        "equity": 0.1658,
        "tier": "C"
      },
      {
        "code": "74s",
        "kind": "suited",
        "equity": 0.1491,
        "tier": "C"
      },
      {
        "code": "73s",
        "kind": "suited",
        "equity": 0.1389,
        "tier": "D"
      },
      {
        "code": "72s",
        "kind": "suited",
        "equity": 0.1292,
        "tier": "D"
      }
    ],
    [
      {
        "code": "A6o",
        "kind": "offsuit",
        "equity": 0.1728,
        "tier": "C"
      },
      {
        "code": "K6o",
        "kind": "offsuit",
        "equity": 0.1611,
        "tier": "C"
      },
      {
        "code": "Q6o",
        "kind": "offsuit",
        "equity": 0.1413,
        "tier": "D"
      },
      {
        "code": "J6o",
        "kind": "offsuit",
        "equity": 0.1303,
        "tier": "D"
      },
      {
        "code": "T6o",
        "kind": "offsuit",
        "equity": 0.1319,
        "tier": "D"
      },
      {
        "code": "96o",
        "kind": "offsuit",
        "equity": 0.1334,
        "tier": "D"
      },
      {
        "code": "86o",
        "kind": "offsuit",
        "equity": 0.136,
        "tier": "D"
      },
      {
        "code": "76o",
        "kind": "offsuit",
        "equity": 0.1423,
        "tier": "D"
      },
      {
        "code": "66",
        "kind": "pair",
        "equity": 0.2065,
        "tier": "B"
      },
      {
        "code": "65s",
        "kind": "suited",
        "equity": 0.1703,
        "tier": "C"
      },
      {
        "code": "64s",
        "kind": "suited",
        "equity": 0.1589,
        "tier": "C"
      },
      {
        "code": "63s",
        "kind": "suited",
        "equity": 0.1427,
        "tier": "D"
      },
      {
        "code": "62s",
        "kind": "suited",
        "equity": 0.1326,
        "tier": "D"
      }
    ],
    [
      {
        "code": "A5o",
        "kind": "offsuit",
        "equity": 0.1808,
        "tier": "C"
      },
      {
        "code": "K5o",
        "kind": "offsuit",
        "equity": 0.151,
        "tier": "C"
      },
      {
        "code": "Q5o",
        "kind": "offsuit",
        "equity": 0.1375,
        "tier": "D"
      },
      {
        "code": "J5o",
        "kind": "offsuit",
        "equity": 0.1295,
        "tier": "D"
      },
      {
        "code": "T5o",
        "kind": "offsuit",
        "equity": 0.1179,
        "tier": "D"
      },
      {
        "code": "95o",
        "kind": "offsuit",
        "equity": 0.1201,
        "tier": "D"
      },
      {
        "code": "85o",
        "kind": "offsuit",
        "equity": 0.1246,
        "tier": "D"
      },
      {
        "code": "75o",
        "kind": "offsuit",
        "equity": 0.1225,
        "tier": "D"
      },
      {
        "code": "65o",
        "kind": "offsuit",
        "equity": 0.1326,
        "tier": "D"
      },
      {
        "code": "55",
        "kind": "pair",
        "equity": 0.1867,
        "tier": "C"
      },
      {
        "code": "54s",
        "kind": "suited",
        "equity": 0.162,
        "tier": "C"
      },
      {
        "code": "53s",
        "kind": "suited",
        "equity": 0.1483,
        "tier": "C"
      },
      {
        "code": "52s",
        "kind": "suited",
        "equity": 0.1399,
        "tier": "D"
      }
    ],
    [
      {
        "code": "A4o",
        "kind": "offsuit",
        "equity": 0.1772,
        "tier": "C"
      },
      {
        "code": "K4o",
        "kind": "offsuit",
        "equity": 0.1514,
        "tier": "C"
      },
      {
        "code": "Q4o",
        "kind": "offsuit",
        "equity": 0.133,
        "tier": "D"
      },
      {
        "code": "J4o",
        "kind": "offsuit",
        "equity": 0.1161,
        "tier": "D"
      },
      {
        "code": "T4o",
        "kind": "offsuit",
        "equity": 0.1134,
        "tier": "D"
      },
      {
        "code": "94o",
        "kind": "offsuit",
        "equity": 0.1024,
        "tier": "D"
      },
      {
        "code": "84o",
        "kind": "offsuit",
        "equity": 0.1103,
        "tier": "D"
      },
      {
        "code": "74o",
        "kind": "offsuit",
        "equity": 0.1113,
        "tier": "D"
      },
      {
        "code": "64o",
        "kind": "offsuit",
        "equity": 0.119,
        "tier": "D"
      },
      {
        "code": "54o",
        "kind": "offsuit",
        "equity": 0.1282,
        "tier": "D"
      },
      {
        "code": "44",
        "kind": "pair",
        "equity": 0.1697,
        "tier": "C"
      },
      {
        "code": "43s",
        "kind": "suited",
        "equity": 0.1428,
        "tier": "D"
      },
      {
        "code": "42s",
        "kind": "suited",
        "equity": 0.1328,
        "tier": "D"
      }
    ],
    [
      {
        "code": "A3o",
        "kind": "offsuit",
        "equity": 0.1755,
        "tier": "C"
      },
      {
        "code": "K3o",
        "kind": "offsuit",
        "equity": 0.1478,
        "tier": "D"
      },
      {
        "code": "Q3o",
        "kind": "offsuit",
        "equity": 0.1245,
        "tier": "D"
      },
      {
        "code": "J3o",
        "kind": "offsuit",
        "equity": 0.1167,
        "tier": "D"
      },
      {
        "code": "T3o",
        "kind": "offsuit",
        "equity": 0.1077,
        "tier": "D"
      },
      {
        "code": "93o",
        "kind": "offsuit",
        "equity": 0.1032,
        "tier": "D"
      },
      {
        "code": "83o",
        "kind": "offsuit",
        "equity": 0.094,
        "tier": "D"
      },
      {
        "code": "73o",
        "kind": "offsuit",
        "equity": 0.1019,
        "tier": "D"
      },
      {
        "code": "63o",
        "kind": "offsuit",
        "equity": 0.1099,
        "tier": "D"
      },
      {
        "code": "53o",
        "kind": "offsuit",
        "equity": 0.1186,
        "tier": "D"
      },
      {
        "code": "43o",
        "kind": "offsuit",
        "equity": 0.1034,
        "tier": "D"
      },
      {
        "code": "33",
        "kind": "pair",
        "equity": 0.1649,
        "tier": "C"
      },
      {
        "code": "32s",
        "kind": "suited",
        "equity": 0.1277,
        "tier": "D"
      }
    ],
    [
      {
        "code": "A2o",
        "kind": "offsuit",
        "equity": 0.158,
        "tier": "C"
      },
      {
        "code": "K2o",
        "kind": "offsuit",
        "equity": 0.1391,
        "tier": "D"
      },
      {
        "code": "Q2o",
        "kind": "offsuit",
        "equity": 0.1226,
        "tier": "D"
      },
      {
        "code": "J2o",
        "kind": "offsuit",
        "equity": 0.1164,
        "tier": "D"
      },
      {
        "code": "T2o",
        "kind": "offsuit",
        "equity": 0.1042,
        "tier": "D"
      },
      {
        "code": "92o",
        "kind": "offsuit",
        "equity": 0.0933,
        "tier": "D"
      },
      {
        "code": "82o",
        "kind": "offsuit",
        "equity": 0.0868,
        "tier": "D"
      },
      {
        "code": "72o",
        "kind": "offsuit",
        "equity": 0.0907,
        "tier": "D"
      },
      {
        "code": "62o",
        "kind": "offsuit",
        "equity": 0.0934,
        "tier": "D"
      },
      {
        "code": "52o",
        "kind": "offsuit",
        "equity": 0.0977,
        "tier": "D"
      },
      {
        "code": "42o",
        "kind": "offsuit",
        "equity": 0.09,
        "tier": "D"
      },
      {
        "code": "32o",
        "kind": "offsuit",
        "equity": 0.086,
        "tier": "D"
      },
      {
        "code": "22",
        "kind": "pair",
        "equity": 0.1607,
        "tier": "C"
      }
    ]
  ]
}
